stages:
  - build_test

build-test:
  stage: build_test
  image: docker:24.0
  tags:
    - windows
  services:
    - docker:24.0-dind
  variables:
    #DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    COMPOSE_PROJECT_NAME: grawe_ci

  before_script:
    - apk add --no-cache docker-compose curl bash

  script:
    - docker-compose config

    - docker-compose up -d

    - sleep 60
    - docker-compose ps
    - docker-compose logs server

  after_script:
    - docker-compose down -v


  when: manual