stages:
  - smoke_test

variables:
  COMPOSE_PROJECT_NAME: grawe_ci

smoke-test:
  stage: smoke_test
  image: docker:24.0
  tags:
    - windows
  services:
    - docker:24.0-dind
  variables:
    # Critical Docker-in-Docker configuration
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    
    # Project-specific variables
    COMPOSE_PROJECT_NAME: grawe_ci

  before_script:
    - apk add --no-cache docker-compose
    # Ensure Docker daemon is fully up and running
    - until docker info; do sleep 1; done

  script:
    # Verbose debugging steps
    - docker version
    - docker info
    - docker-compose version
    
    # Prepare environment
    - docker-compose config  # Validate compose file
    
    # Run services
    - docker-compose up -d
    
    # Extended service startup wait
    - sleep 60
    
    # Check service status
    - docker-compose ps
    - docker-compose logs server

  after_script:
    - docker-compose down -v
  
  # Allow manual trigger for easier debugging
  when: manual