smoke-test:
  stage: smoke_test
  image: docker:24.0
  tags:
    - windows
  services:
    - name: docker:24.0-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker info  # Verify Docker daemon connection
    - docker-compose up -d
    - sleep 30  # Increased sleep time for services to start
    - docker-compose ps
    - docker-compose logs --tail=50 server
  after_script:
    - docker-compose down -v