stages:
  - build

# Use this to define variables for the entire pipeline
variables:
  # Add your environment variables here
  SQL_PASSWORD: ${SQL_PASSWORD}
  REDIS_PASSWORD: ${REDIS_PASSWORD}

build-job:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "Starting build job..."
    - docker-compose build
    - echo "Docker images built successfully"
    - docker-compose up -d
    - sleep 15
    - echo "Checking containers:"
    - docker-compose ps
    # Optional: Run a basic test to verify the application started
    - |
      if docker-compose exec -T server curl -s http://127.0.0.1:3000/api/v1/health; then
        echo "Application is running and healthy"
      else
        echo "Application health check failed"
        docker-compose logs
        exit 1
      fi
    - echo "Build completed successfully!"
  after_script:
    - docker-compose down
  only:
    - dev