stages:
  - build_test
build-test:
  stage: build_test
  image: docker:24.0
  tags:
    - windows
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
    COMPOSE_PROJECT_NAME: grawe_ci
    GIT_DEPTH: 0  # Full clone
  before_script:
    - apk add --no-cache docker-compose curl bash git
  script:
    # Verify local files
    - echo "Local Project Files:"
    - ls -la

    # Detailed Docker build log
    - docker-compose build server --no-cache

    # Start services
    - docker-compose up -d
    - sleep 60

    # Extensive container file investigation
    - |
      docker-compose exec server sh -c "
        echo '--- Current Directory ---';
        pwd;
        echo '--- Root Directory Contents ---';
        ls -la /;
        echo '--- Working Directory Contents ---';
        ls -la /usr/src/app;
        echo '--- Detailed File Tree ---';
        find /usr/src/app | sort
      "

    # Detailed container inspection
    - docker inspect grawe_ci-server-1

    # Docker build logs
    - docker history grawe_ci-server

    # Additional logging
    - docker-compose logs server
  after_script:
    - docker-compose down -v
  when: manual