stages:
  - smoke_test

variables:
  COMPOSE_PROJECT_NAME: grawe_ci

smoke-test:
  stage: smoke_test
  image: docker:24.0
  tags:
    - windows
  services:
    - name: docker:24.0-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    # Docker configuration
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    COMPOSE_PROJECT_NAME: grawe_ci

    # Server configuration
    NODE_ENV: development
    PORT: "3000"
    HOST: localhost
    HOST_URL: http://localhost:3000
    API_VERSION: v1

    # Authentication
    JWT_ENCRYPT_PWD: superAwesomePasswordStringThatIsAtLeast32CharactersLong9128370128937120893712089ulasjhasldjhas!
    JWT_EXPIRES_IN: 1h
    COOKIE_ENCRYPT_PWD: superAwesomePasswordStringThatIsAtLeast32CharactersLong9128370128937120893712089ulasjhasldjhas!

    # SQL Server connection
    SQL_USER: SA
    SQL_PASSWORD: Grawe123$
    SQL_DATABASE: GRAWE_WEBAPP
    SQL_SERVER: 172.23.0.20
    SQL_ENCRYPT: "false"
    SQL_DATABASE_TEST: GRAWE_WEBAPP_TEST

    # Redis connection
    REDIS_ENABLED: "true"
    REDIS_HOST: 172.23.0.22
    REDIS_PORT: "6379"
    REDIS_PASSWORD: Grawe123$

    # Superset configuration
    SUPERSET_SECRET_KEY: G6@W3123!@*
    SECRET_KEY: 27893u1298sj189sj1298uej29m3u13p12mp31283u129083m1
    SUPERSET_ADMIN_USERNAME: admin
    SUPERSET_ADMIN_PASSWORD: admin
    SUPERSET_ADMIN_EMAIL: admin@superset.com
    SUPERSET_ADMIN_FIRSTNAME: Test
    SUPERSET_ADMIN_LASTNAME: Test
    SUPERSET_URL: http://172.23.0.13:8088/api/v1/
    SUPERSET_PORT: "8088"
    SUPERSET_ENV: development
    SUPERSET_LOAD_EXAMPLES: "no"
    SUPERSET_FEATURE_EMBEDDED_SUPERSET: "true"
    SUPERSET_USERNAME: admin
    SUPERSET_PASSWORD: admin

    # Postgres configuration
    POSTGRES_DB: superset
    POSTGRES_USER: superset
    POSTGRES_PASSWORD: superset
    DATABASE_DIALECT: postgresql
    SQLALCHEMY_DATABASE_URI: postgresql://superset:superset@host.docker.internal:5432/superset

    # Superset Redis configuration
    SUPERSET_REDIS_HOST: redis
    SUPERSET_REDIS_PORT: "6379"
    SUPERSET_REDIS_PASSWORD: Grawe123$
    SUPERSET_REDIS_DB: "1"

  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker info  # Verify Docker daemon connection
    - docker-compose config  # Verify compose configuration
    - docker-compose up -d
    - sleep 45  # Increased sleep time for services to start
    - docker-compose ps
    - docker-compose logs --tail=50 server
  after_script:
    - docker-compose down -v
  when: manual  # Optional: makes the job manually triggerable