stages:
  - smoke_test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: grawe_ci

services:
  - docker:20.10.16-dind

before_script:
  - apk add --no-cache docker-compose

smoke-test:
  stage: smoke_test
  script:
    - docker-compose up -d
    - sleep 30  # Wait for services to initialize
    - docker-compose ps
    - docker-compose logs --tail=50 server  # Check server logs
  after_script:
    - docker-compose down -v