version: '3'



services:
#  server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'                 # Map the server container's port 3000 to the host's port 3000
#    environment:
#      - DB_HOST=localhost
#      - DB_USER=SA
#      - DB_PASSWORD=Grawe123$
#      - REDIS_HOST=172.23.0.22
#      - REDIS_PORT=6379
#      - REDIS_PASSWORD=Grawe123$

#    volumes:
#      - ./:/usr/src/app
#      - /usr/src/app/node_modules
      #- ./node_modules:/usr/src/app/node_modules

#    restart: on-failure
#    depends_on:
     # - mssql-server
#      - cache
#    networks:
#      mynetwork:
#        ipv4_address: 172.23.0.21
#    command: ["sh", "-c", "sleep 3 && npm start"]

#  mssql-server:
    #image: mcr.microsoft.com/mssql/server:latest
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    init: true
#    environment:
#      - ACCEPT_EULA=Y               # Accept the MSSQL EULA
#      - SA_PASSWORD=Grawe123$
#      - MSSQL_PID=Express           # Set the SQL Server Edition
#    ports:
#      - '1433:1433'                 # Map the MSSQL container's port 1433 to the host's port 1433
#    volumes:
#      - ./mssql-data/data:/var/opt/mssql/data
#      - ./mssql-data/log:/var/opt/mssql/log
#     - ./mssql-data/secrets:/var/opt/mssql/secrets


#    networks:
#      mynetwork:
 #       ipv4_address: 172.23.0.23


  cache:
    image: redis:alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass Grawe123$
    ports:
      - '6379:6379'
    volumes:
      - ./cache:/data
    restart: always

    networks:
      mynetwork:
        ipv4_address: 172.23.0.22

  ldap:
    image: osixia/openldap
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ORGANISATION="GRAWE"
      - LDAP_DOMAIN="grawe.local"
      - LDAP_ADMIN_PASSWORD=Grawe123$
      - LDAP_CONFIG_PASSWORD=Grawe123$
      - LDAP_READONLY_USER=false
      - LDAP_READONLY_USER_USERNAME=grawe
      - LDAP_READONLY_USER_PASSWORD=Grawe123$
      - LDAP_TLS=false
    volumes:
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    restart: always

    networks:
      mynetwork:
        ipv4_address: 172.23.0.21

  phpldapadmin:
    image: osixia/phpldapadmin
    ports:
      - '8080:80'
    environment:
        - PHPLDAPADMIN_LDAP_HOSTS=ldap
        - PHPLDAPADMIN_HTTPS=false
    restart: always

    networks:
      mynetwork:
        ipv4_address: 172.23.0.23


networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/24"
        


#<<<<<<< Updated upstream
#  superset:
#    build:
#      context: .
#      dockerfile: ./superset/Dockerfile
#    image: apache/superset
#    depends_on:
#      - mssql-server
#    ports:
#      - '8088:8088'
   # volumes:
   #   - ./superset:/usr/src/app/superset/
#    environment:
#      - SUPERSET_LOAD_EXAMPLES=no
#      - SUPERSET_DATABASE_URI=mssql+pymssql://sa:Grawe123$@172.23.0.23:1433/GRAWE
      #-'mssql+pyodbc://@' + localhost + '/' + dbname + '?trusted_connection=yes&driver=ODBC+Driver+13+for+SQL+Server'
#      - SUPERSET_SECRET_KEY=grawe123$
#      - SUPERSET_WEBSERVER_PORT=8088
#      - SUPERSET_WEBSERVER_TIMEOUT=6000
#      - SUPERSET_WEBSERVER_WORKERS=10
#      - SUPERSET_WEBSERVER_THREADS=10
#      - SUPERSET_WEBSERVER_MAX_REQUESTS=1000
        #- ADMIN_USERNAME=admin
#=======
  #superset:
  #  build:
  #    context: .
  #    dockerfile: ./superset/Dockerfile
  #  image: apache/superset
  #  depends_on:
  #    - mssql-server
  #  ports:
  #    - '8088:8088'
  #  volumes:
  #    - ./superset:/usr/src/app/superset/
  #  environment:
  #    - SUPERSET_LOAD_EXAMPLES=no
  #    - SUPERSET_DATABASE_URI=mssql+pymssql://sa:Grawe123$@172.23.0.23:1433/GRAWE
      #-'mssql+pyodbc://@' + localhost + '/' + dbname + '?trusted_connection=yes&driver=ODBC+Driver+13+for+SQL+Server'
  #    - SUPERSET_SECRET_KEY=grawe123$
  #    - SUPERSET_WEBSERVER_PORT=8088
  #    - SUPERSET_WEBSERVER_TIMEOUT=6000
  #    - SUPERSET_WEBSERVER_WORKERS=10
  #    - SUPERSET_WEBSERVER_THREADS=10
  #    - SUPERSET_WEBSERVER_MAX_REQUESTS=1000
  #      #- ADMIN_USERNAME=admin
#>>>>>>> Stashed changes
        #- ADMIN_EMAIL=admin@superset.com
        #- ADMIN_PASSWORD=admin


  #  networks:
   #   mynetwork:
   #     ipv4_address: 172.23.0.18


