services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=localhost
      - API_VERSION=v1
      # SQL Server connection
      - SQL_USER=sa
      - SQL_PASSWORD=Grawe123$
      - SQL_DATABASE=GRAWE_DEV
      - SQL_SERVER=172.28.1.2
      - SQL_ENCRYPT=false
      # Authentication
      - JWT_ENCRYPT_PWD=CiEncrypt!
      - JWT_EXPIRES_IN=1h
      - COOKIE_ENCRYPT_PWD=CiEncrypt!
    networks:
      app-network:
        ipv4_address: 172.28.1.3
    command: ["sh", "-c", "sleep 30 && npm start"]
    depends_on:
      - mssql-server

  mssql-server:
    build:
      context: .
      dockerfile: mssql/sqlserver.ci.Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Grawe123$
      - MSSQL_PID=Developer
    volumes:
      - ./mssql/migrations:/usr/src/sql
    ports:
      - '1433:1433'
    networks:
      app-network:
        ipv4_address: 172.28.1.2


networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24