version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REDIS_HOST=172.23.0.22
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
    depends_on:
      - mssql-server
      - cache
    networks:
      mynetwork:
        ipv4_address: 172.23.0.21
    command: ["sh", "-c", "sleep 30 && npm start"]

  mssql-server:
    build:
      context: .
      dockerfile: mssql/sqlserver.Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - '1433:1433'
    volumes:
      - ./mssql-data/data:/var/opt/mssql/data
      - ./mssql-data/log:/var/opt/mssql/log
      - ./mssql-data/secrets:/var/opt/mssql/secrets
      - ./migrations:/usr/src/sql
    networks:
      mynetwork:
        ipv4_address: 172.23.0.20

  cache:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    image: redis:7.2-alpine
    command: sh -c "./init.sh"
    ports:
      - '6379:6379'
    privileged: true
    volumes:
      - ./cache:/data
    restart: always
    environment:
      - ProtectedMode=no
    networks:
      mynetwork:
        ipv4_address: 172.23.0.22

  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
    ports:
      - '8088:8088'
    depends_on:
      - superset-db
      - cache
    volumes:
      - ./superset/db:/app/superset/superset_home/
    environment:
      # Core Superset Configuration
      - SUPERSET_ENV=${SUPERSET_ENV}
      - SUPERSET_LOAD_EXAMPLES=${SUPERSET_LOAD_EXAMPLES}
      - SUPERSET_PORT=${SUPERSET_PORT}
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}

      # Admin User Configuration
      - ADMIN_USERNAME=${SUPERSET_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD}
      - ADMIN_EMAIL=${SUPERSET_ADMIN_EMAIL}
      - ADMIN_FIRSTNAME=${SUPERSET_ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${SUPERSET_ADMIN_LASTNAME}

      # Database Configuration
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - DATABASE_DB=${POSTGRES_DB}
      - DATABASE_HOST=superset-db
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_USER=${POSTGRES_USER}

      # Redis Configuration
      - REDIS_HOST=${SUPERSET_REDIS_HOST}
      - REDIS_PORT=${SUPERSET_REDIS_PORT}

      # Feature Configuration
      - SUPERSET_FEATURE_EMBEDDED_SUPERSET=${SUPERSET_FEATURE_EMBEDDED_SUPERSET}
      - PYTHONPATH=/app/pythonpath:/app/docker/pythonpath_dev

      # Flask Configuration
      - FLASK_DEBUG=true
    networks:
      mynetwork:
        ipv4_address: 172.23.0.13

  superset-db:
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./superset/data:/var/lib/postgresql/data
      - ./superset/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      mynetwork:
        ipv4_address: 172.23.0.23

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/24"