const correct_policies_values = [
  {
    Broj_Polise: 5027,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 1995.6,
    Neto_polisirana_premija: 1830.84,
    Premija: 1995.6,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'GRAWE NEŽIVOTNO OSIGURANJE AD',
    Ugovarac: 'HG BUDVANSKA RIVIJERA AD',
  },
  {
    Broj_Polise: 5030,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 1306.32,
    Neto_polisirana_premija: 1198.44,
    Premija: 1306.32,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'BROKER INS',
    Ugovarac: 'CARINVEST DOO',
  },
  {
    Broj_Polise: 1001195,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 5265.48,
    Neto_polisirana_premija: 4830.68,
    Premija: 5265.48,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'SWISS PLUS DOO',
    Ugovarac: 'ZU POLIKLINIKA STOJANOVIĆ MEDIK',
  },
  {
    Broj_Polise: 1001291,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 3861.84,
    Neto_polisirana_premija: 3542.83,
    Premija: 3861.84,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'INSURANCE FINANCIAL SOLUTIONS',
    Ugovarac: 'FILAN COMPANY DOO',
  },
  {
    Broj_Polise: 1001300,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 592.92,
    Neto_polisirana_premija: 543.93,
    Premija: 592.92,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'ZORAN FRANETA',
    Ugovarac: 'JANOVIĆ SVETLANA',
  },
  {
    Broj_Polise: 1001350,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 748.32,
    Neto_polisirana_premija: 686.52,
    Premija: 748.32,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'STATUS BROKER',
    Ugovarac: 'DONATOR DOO',
  },
  {
    Broj_Polise: 1001381,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 727.2,
    Neto_polisirana_premija: 667.02,
    Premija: 727.2,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'STATUS BROKER',
    Ugovarac: 'JANJEVIĆ DRAGAN',
  },
  {
    Broj_Polise: 1001573,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 13579.56,
    Neto_polisirana_premija: 12458.34,
    Premija: 13579.56,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'GRAWE NEŽIVOTNO OSIGURANJE AD',
    Ugovarac: 'HG BUDVANSKA RIVIJERA AD',
  },
  {
    Broj_Polise: 1001577,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 1259.88,
    Neto_polisirana_premija: 1155.71,
    Premija: 1259.88,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'TIHOMIR MAROVIĆ',
    Ugovarac: 'SRETEN PETROVIC',
  },
  {
    Broj_Polise: 1001643,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 1779.56,
    Neto_polisirana_premija: 1632.6,
    Premija: 1779.56,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'OMEGA BROKER',
    Ugovarac: 'JZU DOM ZDRAVLJA BUDVA',
  },
  {
    Broj_Polise: 4020012,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 19840.38,
    Neto_polisirana_premija: 18202.2,
    Premija: 19840.38,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'INSURANCE FINANCIAL SOLUTIONS',
    Ugovarac: 'KONZORCIJUM KOLUBARA DOO I HSV',
  },
  {
    Broj_Polise: 5100098,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 755.94,
    Neto_polisirana_premija: 693.5,
    Premija: 755.94,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'WVP DOO',
    Ugovarac: 'RS ELLITE',
  },
  {
    Broj_Polise: 5100115,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 3486.96,
    Neto_polisirana_premija: 3198.77,
    Premija: 3486.96,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'AMON BROKER DOO',
    Ugovarac: 'ALGORITAM D.O.O.',
  },
  {
    Broj_Polise: 9002971,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 686.04,
    Neto_polisirana_premija: 686.08,
    Premija: 686.04,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'LAZAR IKOVIĆ',
    Ugovarac: 'MONTENEGRO INVESTMENTS CREDIT D',
  },
  {
    Broj_Polise: 91065968,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 71.79,
    Neto_polisirana_premija: 65.86,
    Premija: 71.79,
    Status_Polise: 'Prekid',
    Naziv_zastupnika: 'ŽELJKA RADULOVIĆ',
    Ugovarac: 'PLAKALO ALEN',
  },
  {
    Broj_Polise: 91068184,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 44.93,
    Neto_polisirana_premija: 41.22,
    Premija: 44.93,
    Status_Polise: 'Prekid',
    Naziv_zastupnika: 'SWISS PLUS DOO',
    Ugovarac: 'ĐURKOVIĆ MARKO',
  },
  {
    Broj_Polise: 98024600,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 771.48,
    Neto_polisirana_premija: 707.78,
    Premija: 771.48,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'NEŠKO TOMIĆ',
    Ugovarac: 'ČVOROVIĆ DOO',
  },
  {
    Broj_Polise: 98025021,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 2466.02,
    Neto_polisirana_premija: 2262.4,
    Premija: 2466.02,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'INSURANCE FINANCIAL SOLUTIONS',
    Ugovarac: 'HIPOTEKARNA BANKA AD',
  },
  {
    Broj_Polise: 98025125,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 255.95,
    Neto_polisirana_premija: 234.82,
    Premija: 255.95,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'ŽELJKO VUKČEVIĆ',
    Ugovarac: 'ENTEXT D.O.O.',
  },
  {
    Broj_Polise: 98025129,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 626.51,
    Neto_polisirana_premija: 574.78,
    Premija: 626.51,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'NEŠKO TOMIĆ',
    Ugovarac: 'BJELICA NIKOLA',
  },
  {
    Broj_Polise: 98025132,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 327.97,
    Neto_polisirana_premija: 300.89,
    Premija: 327.97,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'ZORAN BULATOVIĆ',
    Ugovarac: 'TOŠIĆ OBREN',
  },
  {
    Broj_Polise: 98025255,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 850.75,
    Neto_polisirana_premija: 780.5,
    Premija: 850.75,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'NEŠKO TOMIĆ',
    Ugovarac: 'NOVAK RADULOVIĆ',
  },
  {
    Broj_Polise: 98025633,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 850.45,
    Neto_polisirana_premija: 780.23,
    Premija: 850.45,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'DANILO GOJKOVIĆ',
    Ugovarac: 'CARINVEST DOO',
  },
  {
    Broj_Polise: 98025773,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 532.11,
    Neto_polisirana_premija: 488.17,
    Premija: 532.11,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'DRAGANA RADOVIĆ',
    Ugovarac: 'MANOJLOVIC MILADIN',
  },
  {
    Broj_Polise: 98025964,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 797.65,
    Neto_polisirana_premija: 731.79,
    Premija: 797.65,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'NEŠKO TOMIĆ',
    Ugovarac: 'HALOTAKSI DOO',
  },
  {
    Broj_Polise: 98026065,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 580.98,
    Neto_polisirana_premija: 533.01,
    Premija: 580.98,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'ZORAN FRANETA',
    Ugovarac: 'ROGANOVIC DOO BUDVA',
  },
  {
    Broj_Polise: 98026096,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 347.06,
    Neto_polisirana_premija: 318.4,
    Premija: 347.06,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'VELIBOR JUŠKOVIĆ',
    Ugovarac: 'IVAN BRACANOVIĆ',
  },
  {
    Broj_Polise: 98026205,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 853.31,
    Neto_polisirana_premija: 782.85,
    Premija: 853.31,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'VELIBOR JUŠKOVIĆ',
    Ugovarac: 'DROBNJAK ŽELJKO',
  },
  {
    Broj_Polise: 98026289,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 28.19,
    Neto_polisirana_premija: 25.86,
    Premija: 28.19,
    Status_Polise: 'Prekid',
    Naziv_zastupnika: 'SANJA BOŽOVIĆ',
    Ugovarac: 'ROKŠPED AUTO CENTAR DOO',
  },
  {
    Broj_Polise: 98026393,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 362.49,
    Neto_polisirana_premija: 332.56,
    Premija: 362.49,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'ŽELJKO VUKČEVIĆ',
    Ugovarac: 'MONTE RENTAL DOO',
  },
  {
    Broj_Polise: 98026542,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 1042.67,
    Neto_polisirana_premija: 956.58,
    Premija: 1042.67,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'INSURANCE FINANCIAL SOLUTIONS',
    Ugovarac: 'BM MONTENEGRO DOO',
  },
  {
    Broj_Polise: 98026668,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 861.31,
    Neto_polisirana_premija: 790.19,
    Premija: 861.31,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'MILOŠ KNEŽEVIĆ',
    Ugovarac: 'DRAGAN ĐURKOVIĆ',
  },
  {
    Broj_Polise: 98026727,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 589.11,
    Neto_polisirana_premija: 540.47,
    Premija: 589.11,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'NEŠKO TOMIĆ',
    Ugovarac: 'KOLUNDŽIĆ DOO',
  },
  {
    Broj_Polise: 98026743,
    Pol_kreis: 99,
    Bruto_polisirana_premija: 2515.18,
    Neto_polisirana_premija: 2307.5,
    Premija: 2515.18,
    Status_Polise: 'Aktivna',
    Naziv_zastupnika: 'INSURANCE FINANCIAL SOLUTIONS',
    Ugovarac: 'KROLBAY DOO',
  },
];

module.exports = {
  correct_policies_values,
};
